name: Check Sender ID

on:
  push:
    branches: [ main ]

jobs:
  print_id:
    runs-on: ubuntu-latest
    steps:
    - name: Print sender ID
      run: echo "The sender ID is: ${{ github.event.sender.id }}"